// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjqluekvqdompfpyucjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqcWx1ZWt2cWRvbXBmcHl1Y2pnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxMjEzNDAsImV4cCI6MjA1NDY5NzM0MH0.4gSWZ2HOKee5UGmpuKLdgvkyI9UdxqUI2WZ0XUP80_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);